### ISSUE TITLE
Ручное называние файлов в папке компонента

### ISSUE THREAD

**Issue by glebgorokhov** [verstaburo/versta-project-template#1]
**Очень много лишних действий.**
Чтобы создать новый блок, надо:

1. Сделать копию папки с пустыми scss, pug и js файлами
2. Назвать ее
3. Назвать .scss файл
4. Назвать .pug файл
5. Назвать .js (если нужен) файл

Надо попробовать изменить подход, чтобы было:

1. Сделать копию папки с пустыми scss, pug и js файлами
2. Назвать ее

Т.е. папка-заготовка должна включать в себя файлы:

- template.pug
- style.scss
- scripts.js

**Надо подумать над реализацией**

**Comment by dontlemmedown** [comment]
Будет так: 

npm run make-block blockName
npm run make-component blockName
npm run make-page pageName


Вот код у CSSSR https://github.com/CSSSR/csssr-project-template/blob/master/make-block.js

Нам нужно будет добавить еще пару типов блоков (компонент, страница), возможно в CLI добавить выбор необходимых файлов, т.е, пишем.

npm run make-block
>>> Enter block name
>>> Select files
- JS
- PUG
- SCSS

А по дефолту, когда пишем npm run make-block header (будет генерироваться только scss и pug) файл, ибо, js нужен куда реже.

**Comment by glebgorokhov** [comment]
Норм. Делай.
Последним параметром можно сделать че-нибудь типа js, чтобы он добавлял и js файл тоже

`npm run make-block blockName js`

**Comment by dontlemmedown** [comment]
@glebgorokhov 
Добавил создание блоков, страниц, компонентов, обновил ридми.
Нужно тестить.
