### ISSUE TITLE
Потеря стилей у иконок при генерации спрайта

### ISSUE THREAD

**Issue by glebgorokhov** [verstaburo/versta-project-template#6]
Есть сложные иконки, которые одновременно регулируются и fill, и stroke для отдельных векторов. При генерации спрайта эти атрибуты пропадают. Можно ли как-то отрегулировать этот момент? Например, придумать какой-то атрибут, добавляемый к исходному svg, при наличии которого инлайновые fill/stroke не будут пропадать?

**Comment by dontlemmedown** [comment]
fill, stroke вырезаются специально (мы обсуждали) траблы с хромом.

> Например, придумать какой-то атрибут
Можно попробовать, но, я не уверен, что это нужно.

> Есть сложные иконки
Покажи пример подобной иконки

**Comment by glebgorokhov** [comment]
http://verstaburo.com/work/TIS/index.php
http://prntscr.com/f8g8di
У этих иконок у разных слоев разная прозрачность, хотя цвет один.

А вот иконка, у которой кружок внутри заполнен белым, а остальная часть другим цветом. Хорошо бы иметь возможность прописывать какие-то стили (например, белую заливку в этой иконке или прозрачность в примере выше) внутри svg
https://verstaburo.github.io/wikipravo/
http://prntscr.com/f8g8x5

**Comment by dontlemmedown** [comment]
@glebgorokhov  opacity не порежет, насчет иконки 2х и более цветной, по логике, она не должна быть в свг спрайте, ибо покрасить ее (нормально) все равно нельзя, поэтому, ее нужно сохранять картинкой.
Но, конкретно в это примере, это фейл дизайнера, круг явно должен был быть вырезан.
Но, в любом случае, можно обратиться к элементам svg
https://jsfiddle.net/mfLex6cs/

**Comment by glebgorokhov** [comment]
Через use ты так не обратишься
Покрасить можно. Просто у белого круга задается fill, а у остальной иконки - нет. Тогда через svg {fill: #...} будет краситься только та часть, у которой не указан цвет.

Что фейл дизайнера, в данном случае это так, но иногда это задумка, что часть svg красится, а часть нет.

**Comment by dontlemmedown** [comment]
@glebgorokhov в таком случае, придется отключить вырезание атрибутов stroke/fill и , если нужно, убирать их руками. Отключить?

**Comment by glebgorokhov** [comment]
Не, отключать не надо, ибо в 90% случаев их надо убирать.

А шо если сделать 2 папки:

/raw-icons/
/icons/

В raw-icons закидываются иконки
В icons они автоматически перемещаются с вырезанием stroke/fill, и из них уже генерируется спрайт. Но если ты в icons обратно вернешь атрибуты, то они в спрайте сохраняются.

**Comment by dontlemmedown** [comment]
@glebgorokhov может с этим не заморачиваться и эти 10% складывать в static/images? Ибо оттуда атрибуты не режутся. 

Просто при продакшн сборке (без вотчинга), у тебя опять все иконки сломаются, т.е они снова переместятся из raw-icons в icons и с каждой сборкой, придется менять эти аттрибуты, уж тогда, лучше сделать 2 отдельных таска, 2 отдельных спрайта и 2 отдельных папки

**Comment by glebgorokhov** [comment]
А тут ты прав, однако. Просто хочется таки какой-то таск сделать для этих свг, ибо убирается всякий мусор из ненужных тегов типа мета-информации и т.д. Мб сделать для этого папку static/images/svg и в ней проводить такую небольшую оптимизацию, чисто уборка мета-тегов и прочего хлама?

**Comment by dontlemmedown** [comment]
@glebgorokhov  static/images так и есть сейчас, оттуда убирается хлам из svg файлов.
Там подключается https://github.com/svg/svgo через imagemin с дефолтными параметрами.

**Comment by glebgorokhov** [comment]
Тада ладно
