### ISSUE TITLE
Сделать пример верстки

### ISSUE THREAD

**Issue by dontlemmedown** [verstaburo/versta-project-template#7]
Думаю, стоит сделать пример верстки на шаблоне.
Страница(ы) должна быть не очень простая, чтобы затронуть все возможности шаблона. 

Верстку, скорее всего, нужно запилить в отдельном бранче, дабы не чистить шаблон на новых проектах.

**Comment by glebgorokhov** [comment]
Угу, тоже об этом думал. Необходимая вещь

**Comment by dontlemmedown** [comment]
Как время появится, можно даже verstaburo.com переверстать;)

**Comment by glebgorokhov** [comment]
Тож необходимо. Но пока не до этого
