### ISSUE TITLE
Ошибка в таске scripts

### ISSUE THREAD

**Issue by alege** [verstaburo/versta-project-template#9]
В результате переносов строки CRLF (консоль хочет LF) в файле ./app/scripts/app.js не выполняется таск scripts
http://joxi.ru/l2ZLKZOT604yrJ
могу запушить рабочий файл сюда, или это фиксить в таске надо?

**Comment by alege** [comment]
http://joxi.ru/l2ZLKZOT604yrJ

**Comment by dontlemmedown** [comment]
Нет, нужно убрать в eslintrc
